{% set version = "1.5.2" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-networktools
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/networktools_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/networktools/networktools_{{ version }}.tar.gz
  sha256: 877045b0560007df40a476f60cb871e05d6264bf6bd49d1e3ddb9668992d5870

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-r.utils
    - r-rcolorbrewer
    - r-cocor
    - r-eigenmodel
    - r-ggplot2
    - r-gridextra
    - r-igraph
    - r-psych
    - r-qgraph
    - r-reshape2
    - r-smacof
    - r-wordcloud
  run:
    - r-base
    - r-r.utils
    - r-rcolorbrewer
    - r-cocor
    - r-eigenmodel
    - r-ggplot2
    - r-gridextra
    - r-igraph
    - r-psych
    - r-qgraph
    - r-reshape2
    - r-smacof
    - r-wordcloud

test:
  commands:
    - $R -e "library('networktools')"           # [not win]
    - "\"%R%\" -e \"library('networktools')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=networktools
  license: GPL-3.0-only
  summary: Includes assorted tools for network analysis. Bridge centrality; goldbricker; MDS, PCA, & eigenmodel network plotting.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
    - izahn
